### ISSUE TITLE
Improve robustness for Demos and User Testing

### ISSUE THREAD

**Issue by LTDakin** [LCOGT/datalab-ui#116]
Goal: Users will soon begin testing PTR education software. We want to make sure that it is in a stable state so that the feedback we get can be more constructive rather than bug testing. This story aims to fix a myriad of small issues that have built up during feature development.

### Tasks grouped by PR
DataSessions PR
- [x] Fix CORS issue for image webworkers so that RGB scaling works in prod
- [x] Fix vue hydration error message
- [x] Fix missing datasessions message on sessions view load
- [x] Fix Bug where deleting the first operation will select the next operation but not filter the data session as selected
- [x] Fix other warning messages
- [x] Fix coloring issue on Datasessions tab view
- [x] Splash if User has no Data sessions
- [x] Fix Navbar not properly displaying you've selected data sessions page

ProjectView PR
- [x] Clearing either Ra, or Dec doesn't clear the Search field
- [x] Warning for search by only ra or only dec
- [x] Possible to get an undefined error from empty ra/dec fields?
- [x] fix other warning messages

Backend PR
- [x] Remove Test operations (Noop, Error, Long)
