### ISSUE TITLE
Analysis Page Fixes

### ISSUE THREAD

**Issue by LTDakin** [LCOGT/datalab-ui#117]
Goal: Users will soon begin testing datalab and we want to make sure that the features are robust so that feedback can be constructive and offer new insights to use cases rather than bug reports. This issue also seeks to improve some of the existing features in anticipation of what students will want like the ability to filter sources by flux.

### Tasks
Datalab output PR fixes
- [x] Fix line profiles of datalab outputs
- [x] Fix download of datalab outputs FITS, TIF, and Jpgs
- [x] For analysis of datalab outputs handle missing source catalog gracefully

CSS and behavior fixes
- [x] Make leaflet source points non-editable but retain a snap behavior for the line profile tool
- [x] Style the leaflet buttons to match the rest of datalab
- [x] Fix css of analysis view such that the image is not overlapping the data
- [x] V-speed dial not being recognized as a component (handle on own branch since its a versioning issue)
